import { createHash } from "node:crypto";
import { chmod, mkdir, readdir, readFile, stat, unlink } from "node:fs/promises";
import { join, resolve } from "node:path";
import { entryId, hostId, projectId, sessionId } from "@oh-my-pi/app-wire";
import type { DurableEntry, EntryId, HostId, ProjectId, SessionId } from "@oh-my-pi/app-wire";
import type { FileSystem, SessionDiscovery, SessionRecord } from "./types.ts";
const realFs: FileSystem = { mkdir: async (path, options) => { await mkdir(path, options); }, chmod: async (path, mode) => { await chmod(path, mode); }, unlink: async path => { try { await unlink(path); } catch {} }, stat: async path => await stat(path), readdir: async path => { const names = await readdir(path, { withFileTypes: true }); return names.filter(entry => entry.isFile() && entry.name.endsWith(".jsonl")).map(entry => join(path, entry.name)); }, readFile: async path => await readFile(path, "utf8") };
export function stableProjectId(cwd: string): ProjectId { return projectId(`project-${createHash("sha256").update(resolve(cwd)).digest("hex").slice(0, 24)}`); }
function asEntry(raw: Record<string, unknown>, host: HostId, session: SessionId): DurableEntry | undefined { if (typeof raw.id !== "string" || typeof raw.type !== "string") return undefined; const id = entryId(raw.id as EntryId); const parentId = raw.parentId === null || typeof raw.parentId === "string" ? (raw.parentId as EntryId | null | undefined) ?? null : null; const timestamp = typeof raw.timestamp === "string" ? raw.timestamp : new Date(0).toISOString(); const { id: _id, parentId: _parent, timestamp: _ts, type, ...data } = raw; return { id, parentId, hostId: host, sessionId: session, kind: type, timestamp, data }; }
export class FileSessionDiscovery implements SessionDiscovery {
  constructor(private readonly root: string, private readonly fs: FileSystem = realFs, private readonly host: HostId = hostId("discovery")) {}
  async list(): Promise<SessionRecord[]> { let files: string[]; try { files = (await this.fs.readdir(this.root)).sort(); } catch { return []; } const found: SessionRecord[] = []; for (const path of files) { try { const lines = (await this.fs.readFile(path)).split(/\r?\n/).filter(Boolean); if (!lines.length) continue; const header = JSON.parse(lines[0]) as Record<string, unknown>; const sid = typeof header.id === "string" ? sessionId(header.id) : sessionId(path.split("/").pop()?.replace(/\.jsonl$/, "") || path); const cwd = typeof header.cwd === "string" ? resolve(header.cwd) : this.root; const entries = lines.slice(1).flatMap(line => { try { const value = asEntry(JSON.parse(line), this.host, sid); return value ? [value] : []; } catch { return []; } }); const fileStat = await this.fs.stat(path); const first = entries.find(entry => entry.kind === "message"); const title = typeof header.title === "string" ? header.title : first ? String(first.data.message ?? "Untitled") : "Untitled"; found.push({ sessionId: sid, path, cwd, projectId: stableProjectId(cwd), title, updatedAt: new Date(fileStat.mtimeMs).toISOString(), status: "idle", entries }); } catch {} } found.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt) || a.sessionId.localeCompare(b.sessionId)); return found; }
}
export { realFs };
