import { Database } from "bun:sqlite";
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { appendFile, chmod, lstat, mkdir, rename, stat, open } from "node:fs/promises";
import { chmodSync, lstatSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { COMMAND_DESCRIPTORS, DEVICE_CAPABILITIES, isCapability, type CommandDescriptor, type DeviceCapability } from "@oh-my-pi/app-wire";

export type Capability = DeviceCapability;
export interface Clock { now(): number; }
export interface Random { bytes(size: number): Uint8Array; }
const realClock: Clock = { now: () => Date.now() };
const realRandom: Random = { bytes: (size) => randomBytes(size) };
const b64 = (value: Uint8Array): string => Buffer.from(value).toString("base64url");
const hash = (salt: Uint8Array, token: string): Buffer => createHash("sha256").update(salt).update(token).digest();
const safe = (value: unknown, max = 256): string | null => typeof value === "string" && value.length > 0 && value.length <= max && !/[\u0000-\u001f\u007f]/u.test(value) ? value : null;
const recordValue = (value: unknown): Record<string, unknown> | null => value !== null && typeof value === "object" && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : null;
const stringField = (row: Record<string, unknown>, key: string): string => { const value = safe(row[key]); if (!value) throw new Error("invalid persisted row"); return value; };
const numberField = (row: Record<string, unknown>, key: string): number => { const value = row[key]; if (typeof value !== "number" || !Number.isFinite(value)) throw new Error("invalid persisted row"); return value; };
const nullableNumber = (row: Record<string, unknown>, key: string): number | null => { const value = row[key]; if (value === null) return null; return numberField(row, key); };
const canonicalIdentity = (identity: RemotePeerIdentity): string => JSON.stringify([identity.nodeId, identity.login, identity.hostId, identity.tailnetIp ?? null]);
const caps = (value: readonly string[]): readonly Capability[] => [...new Set(value.filter(isCapability))];

export interface PairingService { start(connectionId: string, allowedCapabilities: readonly Capability[], ttlMs?: number): PairStart; complete(connectionId: string, code: string, identity: RemotePeerIdentity, metadata: DeviceMetadata, requestedCapabilities: readonly Capability[]): { readonly deviceId: string; readonly token: string; readonly expiresAt: number }; }
export interface DeviceMetadata { readonly label: string; readonly platform?: string; }
export interface DeviceRecord { readonly deviceId: string; readonly identityKey: string; readonly capabilities: readonly Capability[]; readonly metadata: DeviceMetadata; readonly createdAt: number; readonly lastSeenAt: number | null; readonly revokedAt: number | null; readonly epoch: number; }
export interface AuthenticatedPrincipal extends DeviceRecord { readonly authenticatedAt: number; readonly connectionId: string; }
export interface DeviceRegistry { authenticate(deviceId: string, token: string, identity: RemotePeerIdentity, connectionId: string): AuthenticatedPrincipal; get(deviceId: string): DeviceRecord | null; create(record: DeviceRecord, token: string): void; updateMetadata(deviceId: string, metadata: DeviceMetadata, capabilities: readonly Capability[]): void; revoke(deviceId: string, now?: number): void; list(): readonly DeviceRecord[]; close(): void; }
export interface PairStart { readonly code: string; readonly expiresAt: number; }

function digits(random: Random, count: number): string { let out = ""; while (out.length < count) for (const byte of random.bytes(32)) { if (byte >= 250) continue; out += String(byte % 10); if (out.length === count) break; } return out; }

export class SqliteDeviceRegistry implements DeviceRegistry {
  private read(rowValue: unknown): DeviceRecord | null { const row = recordValue(rowValue); if (!row) return null; const capabilityValue: unknown = JSON.parse(stringField(row, "capabilities")); if (!Array.isArray(capabilityValue)) throw new Error("invalid persisted capability"); const validCapabilities = capabilityValue.filter((value): value is Capability => isCapability(value)); if (validCapabilities.length !== capabilityValue.length) throw new Error("invalid persisted capability"); const metadataValue: unknown = JSON.parse(stringField(row, "metadata")); const metadata = recordValue(metadataValue); if (!metadata || typeof metadata.label !== "string" || (metadata.platform !== undefined && typeof metadata.platform !== "string")) throw new Error("invalid persisted metadata"); const deviceMetadata: DeviceMetadata = metadata.platform === undefined ? { label: metadata.label } : { label: metadata.label, platform: metadata.platform }; return { deviceId: stringField(row, "device_id"), identityKey: stringField(row, "identity_key"), capabilities: validCapabilities, metadata: deviceMetadata, createdAt: numberField(row, "created_at"), lastSeenAt: nullableNumber(row, "last_seen_at"), revokedAt: nullableNumber(row, "revoked_at"), epoch: numberField(row, "epoch") }; }
  constructor(path: string, private readonly clock: Clock = realClock, private readonly random: Random = realRandom) {
    if (lstatSync(path, { throwIfNoEntry: false })?.isSymbolicLink()) throw new Error("device database symlink rejected");
    mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
    this.database = new Database(path);
    chmodSync(path, 0o600);
    this.database.run("PRAGMA busy_timeout=5000");
    this.database.run("CREATE TABLE IF NOT EXISTS devices(device_id TEXT PRIMARY KEY, identity_key TEXT NOT NULL, node_id TEXT NOT NULL, login TEXT NOT NULL, host_id TEXT NOT NULL, tailnet_ip TEXT NOT NULL, metadata TEXT NOT NULL, capabilities TEXT NOT NULL, created_at INTEGER NOT NULL, last_seen_at INTEGER, revoked_at INTEGER, epoch INTEGER NOT NULL, salt BLOB NOT NULL, token_digest BLOB NOT NULL)");
  }
  private read(rowValue: unknown): DeviceRecord | null { const row = recordValue(rowValue); if (!row) return null; const capabilityValue: unknown = JSON.parse(stringField(row, "capabilities")); if (!Array.isArray(capabilityValue)) throw new Error("invalid persisted capability"); const validCapabilities = capabilityValue.filter((value): value is Capability => isCapability(value)); if (validCapabilities.length !== capabilityValue.length) throw new Error("invalid persisted capability"); const metadataValue: unknown = JSON.parse(stringField(row, "metadata")); const metadata = recordValue(metadataValue); if (!metadata || typeof metadata.label !== "string" || (metadata.platform !== undefined && typeof metadata.platform !== "string")) throw new Error("invalid persisted metadata"); const deviceMetadata: DeviceMetadata = metadata.platform === undefined ? { label: metadata.label } : { label: metadata.label, platform: metadata.platform }; return { deviceId: stringField(row, "device_id"), identityKey: stringField(row, "identity_key"), capabilities: validCapabilities, metadata: deviceMetadata, createdAt: numberField(row, "created_at"), lastSeenAt: nullableNumber(row, "last_seen_at"), revokedAt: nullableNumber(row, "revoked_at"), epoch: numberField(row, "epoch") }; }
  get(deviceId: string): DeviceRecord | null { return this.read(this.database.query("SELECT * FROM devices WHERE device_id=?").get(deviceId)); }
  create(record: DeviceRecord, token: string): void { if (!safe(token, 4096)) throw new Error("token invalid"); const salt = this.random.bytes(16); this.database.query("INSERT INTO devices(device_id,identity_key,node_id,login,host_id,tailnet_ip,metadata,capabilities,created_at,last_seen_at,revoked_at,epoch,salt,token_digest) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(record.deviceId, record.identityKey, record.identityKey, record.identityKey, record.identityKey, record.identityKey, JSON.stringify(record.metadata), JSON.stringify(record.capabilities), record.createdAt, record.lastSeenAt, record.revokedAt, record.epoch, salt, hash(salt, token)); }
  updateMetadata(deviceId: string, metadata: DeviceMetadata, capabilities: readonly Capability[]): void { if (!safe(metadata.label) || capabilities.some((value) => !isCapability(value))) throw new Error("metadata denied"); this.database.query("UPDATE devices SET metadata=?, capabilities=? WHERE device_id=?").run(JSON.stringify(metadata), JSON.stringify(caps(capabilities)), deviceId); }
  authenticate(deviceId: string, token: string, identity: RemotePeerIdentity, connectionId: string): AuthenticatedPrincipal { const rowValue = this.database.query("SELECT * FROM devices WHERE device_id=?").get(deviceId); const row = recordValue(rowValue); const principal = this.read(rowValue); if (!row || !principal || principal.revokedAt !== null || principal.identityKey !== canonicalIdentity(identity)) throw new Error("authentication denied"); const salt = row.salt; const storedDigest = row.token_digest; if (!(salt instanceof Uint8Array) || !(storedDigest instanceof Uint8Array) || storedDigest.length !== 32 || !safe(token, 4096)) throw new Error("authentication denied"); const actual = hash(salt, token); if (!timingSafeEqual(Buffer.from(storedDigest), actual)) throw new Error("authentication denied"); const now = this.clock.now(); this.database.query("UPDATE devices SET last_seen_at=? WHERE device_id=? AND epoch=?").run(now, deviceId, principal.epoch); return { ...principal, lastSeenAt: now, authenticatedAt: now, connectionId }; }
  revoke(deviceId: string, now = this.clock.now()): void { this.database.query("UPDATE devices SET revoked_at=?, epoch=epoch+1 WHERE device_id=?").run(now, deviceId); }
  list(): readonly DeviceRecord[] { return this.database.query("SELECT * FROM devices ORDER BY created_at").all().map((row) => this.read(row)).filter((value): value is DeviceRecord => value !== null); }
  close(): void { this.database.close(); }
}

export class InMemoryDeviceRegistry implements DeviceRegistry { private readonly records = new Map<string, DeviceRecord>(); private readonly tokens = new Map<string, string>(); constructor(private readonly clock: Clock = realClock) {} get(id: string) { return this.records.get(id) ?? null; } create(record: DeviceRecord, token: string) { this.records.set(record.deviceId, record); this.tokens.set(record.deviceId, token); } updateMetadata(id: string, metadata: DeviceMetadata, capabilities: readonly Capability[]) { const record = this.records.get(id); if (!record) throw new Error("missing device"); this.records.set(id, { ...record, metadata, capabilities: caps(capabilities) }); } authenticate(id: string, token: string, identity: RemotePeerIdentity, connectionId: string): AuthenticatedPrincipal { const record = this.records.get(id); if (!record || record.revokedAt !== null || this.tokens.get(id) !== token || record.identityKey !== canonicalIdentity(identity)) throw new Error("authentication denied"); const now = this.clock.now(); const next = { ...record, lastSeenAt: now }; this.records.set(id, next); return { ...next, authenticatedAt: now, connectionId }; } revoke(id: string, now = this.clock.now()) { const record = this.records.get(id); if (record) this.records.set(id, { ...record, revokedAt: now, epoch: record.epoch + 1 }); } list() { return [...this.records.values()]; } close() {} }

export class SqlitePairingService implements PairingService {
  private readonly pending = new Map<string, { connectionId: string; code: string; expiresAt: number; allowed: readonly Capability[]; attempts: number }>();
  private failedAttempts = 0;
  constructor(private readonly registry: DeviceRegistry, private readonly clock: Clock = realClock, private readonly random: Random = realRandom) {}
  start(connectionId: string, allowedCapabilities: readonly Capability[], ttlMs = 120_000): PairStart { this.prune(); if (!safe(connectionId) || this.pending.size >= 5) throw new Error("pairing capacity reached"); const code = digits(this.random, 6); const expiresAt = this.clock.now() + Math.min(Math.max(ttlMs, 1), 120_000); this.pending.set(code, { connectionId, code, expiresAt, allowed: caps(allowedCapabilities), attempts: 0 }); return { code, expiresAt }; }
  complete(connectionId: string, code: string, identity: RemotePeerIdentity, metadata: DeviceMetadata, requestedCapabilities: readonly Capability[]) { this.prune(); this.failedAttempts += 1; const match = [...this.pending.values()].find((entry) => { const left = Buffer.from(entry.code); const right = Buffer.from(code); return left.length === right.length && timingSafeEqual(left, right); }); if (!match || match.connectionId !== connectionId || match.expiresAt <= this.clock.now() || match.attempts >= 5 || this.failedAttempts > 100) throw new Error("pairing denied"); match.attempts += 1; this.failedAttempts = 0; this.pending.delete(match.code); const granted = requestedCapabilities.filter((value) => match.allowed.includes(value) && isCapability(value)); const token = b64(this.random.bytes(32)); const deviceId = b64(this.random.bytes(12)); const now = this.clock.now(); this.registry.create({ deviceId, identityKey: canonicalIdentity(identity), capabilities: caps(granted), metadata, createdAt: now, lastSeenAt: now, revokedAt: null, epoch: 0 }, token); return { deviceId, token, expiresAt: match.expiresAt }; }
  private prune() { const now = this.clock.now(); for (const [code, entry] of this.pending) if (entry.expiresAt <= now || entry.attempts >= 5) this.pending.delete(code); }
}

export interface AuthorizationRequest { readonly principal: AuthenticatedPrincipal; readonly command: string; readonly capabilities: readonly Capability[]; readonly connectionId: string; readonly sessionId?: string; readonly revision?: number; readonly leaseId?: string; readonly confirmationId?: string; readonly args: Record<string, unknown>; }
export interface AuthorizationGuard { authorize(request: AuthorizationRequest): void; }
export class DefaultAuthorizationGuard implements AuthorizationGuard { constructor(private readonly registry?: DeviceRegistry) {} authorize(request: AuthorizationRequest): void { const descriptor: CommandDescriptor | undefined = COMMAND_DESCRIPTORS[request.command]; const current = this.registry?.get(request.principal.deviceId); if (!descriptor || !current || request.principal.connectionId !== request.connectionId || current.epoch !== request.principal.epoch || current.identityKey !== request.principal.identityKey || request.principal.revokedAt !== null || current.revokedAt !== null || request.principal.capabilities.includes(descriptor.capability) === false || request.capabilities.includes(descriptor.capability) === false) throw new Error("command denied"); if (descriptor.scope === "session" && (!request.sessionId || !request.leaseId)) throw new Error("session lease required"); if (descriptor.revision === "required" && request.revision === undefined) throw new Error("revision required"); if (descriptor.confirmation === "challenge" && !request.confirmationId) throw new Error("confirmation required"); } }

interface Bucket { tokens: number; at: number; }
export class TokenBucketLimiter { private readonly buckets = new Map<string, Bucket>(); constructor(private readonly capacity = 30, private readonly refillPerSecond = 10, private readonly clock: Clock = realClock) {} allow(key: string, cost = 1): boolean { if (!safe(key) || !Number.isFinite(cost) || cost <= 0 || cost > this.capacity) return false; const now = this.clock.now(); const old = this.buckets.get(key) ?? { tokens: this.capacity, at: now }; const elapsed = Math.max(0, now - old.at); const tokens = Math.min(this.capacity, old.tokens + elapsed / 1000 * this.refillPerSecond); if (tokens < cost) { this.buckets.set(key, { tokens, at: now }); return false; } this.buckets.set(key, { tokens: tokens - cost, at: now }); if (this.buckets.size > 2048) this.buckets.delete(this.buckets.keys().next().value ?? key); return true; } }

export type LeaseKind = "controller" | "prompt";
export interface Lease { readonly leaseId: string; readonly owner: string; readonly sessionId: string; readonly kind: LeaseKind; readonly expiresAt: number; }
export class LeaseRegistry { private readonly leases = new Map<string, Lease>(); constructor(private readonly clock: Clock = realClock, private readonly random: Random = realRandom) {} acquire(sessionId: string, owner: string, kind: LeaseKind, ttlMs = 30_000): Lease { this.expire(); if (ttlMs <= 0 || ttlMs > 300_000 || [...this.leases.values()].some((x) => x.sessionId === sessionId && x.kind === kind)) throw new Error("lease held"); const lease = { leaseId: b64(this.random.bytes(12)), owner, sessionId, kind, expiresAt: this.clock.now() + ttlMs }; this.leases.set(lease.leaseId, lease); return lease; } renew(leaseId: string, owner: string, ttlMs = 30_000): Lease { this.expire(); const old = this.leases.get(leaseId); if (!old || old.owner !== owner || ttlMs <= 0 || ttlMs > 300_000) throw new Error("lease denied"); const next = { ...old, expiresAt: this.clock.now() + ttlMs }; this.leases.set(leaseId, next); return next; } release(leaseId: string, owner: string): void { const old = this.leases.get(leaseId); if (old?.owner === owner) this.leases.delete(leaseId); } disconnect(owner: string) { for (const [id, lease] of this.leases) if (lease.owner === owner) this.leases.delete(id); } private expire() { const now = this.clock.now(); for (const [id, lease] of this.leases) if (lease.expiresAt <= now) this.leases.delete(id); } }

export interface ConfirmationGrant { readonly id: string; readonly connectionId: string; readonly deviceId: string; readonly command: string; readonly sessionId: string; readonly argsDigest: string; readonly revision: number; readonly epoch: number; readonly expiresAt: number; }
export const argsDigest = (args: Record<string, unknown>): string => createHash("sha256").update(JSON.stringify(Object.keys(args).sort().reduce<Record<string, unknown>>((out, key) => { out[key] = args[key]; return out; }, {}))).digest("hex");
export class SecureConfirmationStore { private readonly grants = new Map<string, ConfirmationGrant>(); constructor(private readonly clock: Clock = realClock, private readonly random: Random = realRandom) {} issue(input: Omit<ConfirmationGrant, "id" | "expiresAt">, ttlMs = 60_000): ConfirmationGrant { this.prune(); if (this.grants.size >= 5 || ttlMs <= 0) throw new Error("confirmation capacity"); const grant = { ...input, id: b64(this.random.bytes(12)), expiresAt: this.clock.now() + Math.min(ttlMs, 60_000) }; this.grants.set(grant.id, grant); return grant; } consume(id: string, expected: Omit<ConfirmationGrant, "id" | "expiresAt">): void { const grant = this.grants.get(id); this.grants.delete(id); if (!grant || grant.expiresAt <= this.clock.now() || grant.connectionId !== expected.connectionId || grant.deviceId !== expected.deviceId || grant.command !== expected.command || grant.sessionId !== expected.sessionId || grant.argsDigest !== expected.argsDigest || grant.revision !== expected.revision || grant.epoch !== expected.epoch) throw new Error("confirmation denied"); } private prune() { const now = this.clock.now(); for (const [id, grant] of this.grants) if (grant.expiresAt <= now) this.grants.delete(id); } }

export interface Redactor { redact(value: unknown): unknown; }
export class DefaultRedactor implements Redactor { redact(value: unknown): unknown { const seen = new WeakSet<object>(); const walk = (input: unknown, depth: number): unknown => { if (depth > 12) return "[redacted]"; if (Array.isArray(input)) return seen.has(input) ? "[redacted]" : (seen.add(input), input.slice(0, 128).map((x) => walk(x, depth + 1))); if (input && typeof input === "object") { if (seen.has(input)) return "[redacted]"; seen.add(input); const out: Record<string, unknown> = {}; for (const [key, raw] of Object.entries(input).slice(0, 128)) out[key] = /secret|token|auth|password|cookie|credential|private|session|api[-_]?key/iu.test(key) ? "[redacted]" : walk(raw, depth + 1); return out; } if (typeof input === "string" && /bearer\s+|basic\s+|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|-----BEGIN [A-Z ]+PRIVATE KEY-----|[A-Za-z0-9_-]{32,}/iu.test(input)) return "[redacted]"; return input; }; return walk(value, 0); } }
export interface AuditSink { write(event: Record<string, unknown>): Promise<void>; }
export class JsonlAuditSink implements AuditSink { private writing = Promise.resolve(); constructor(private readonly path: string, private readonly redactor: Redactor = new DefaultRedactor(), private readonly maxBytes = 1_048_576) {} write(event: Record<string, unknown>): Promise<void> { this.writing = this.writing.then(async () => { const line = JSON.stringify(this.redactor.redact(event)); if (line.length > this.maxBytes) throw new Error("audit event too large"); await mkdir(dirname(this.path), { recursive: true, mode: 0o700 }); const info = await lstat(this.path).catch(() => null); if (info?.isSymbolicLink()) throw new Error("audit symlink rejected"); if (info && info.size + Buffer.byteLength(line) > this.maxBytes) { await rename(this.path, `${this.path}.${Date.now()}`); } await appendFile(this.path, `${line}\n`, { mode: 0o600 }); await chmod(this.path, 0o600); }); return this.writing; } }

export interface OutboundMessage { readonly kind: "event" | "result" | "error" | "confirmation" | "lease" | "revoke"; readonly payload: unknown; readonly coalesceKey?: string; }
export class OutboundQueue { private readonly items: OutboundMessage[] = []; private bytes = 0; private closed = false; constructor(private readonly hardCap = 1_048_576) {} push(item: OutboundMessage): void { if (this.closed) throw new Error("queue closed"); const bytes = Buffer.byteLength(JSON.stringify(item.payload)); if (bytes > this.hardCap) { this.closed = true; throw new Error("outbound queue hard cap"); } if (item.kind === "event" && item.coalesceKey) { const index = this.items.findIndex((x) => x.kind === "event" && x.coalesceKey === item.coalesceKey); if (index >= 0) { this.bytes -= Buffer.byteLength(JSON.stringify(this.items[index].payload)); this.items.splice(index, 1); } } while (this.bytes + bytes > this.hardCap) { const index = this.items.findIndex((x) => x.kind === "event"); if (index < 0) { this.closed = true; throw new Error("outbound queue hard cap"); } this.bytes -= Buffer.byteLength(JSON.stringify(this.items[index].payload)); this.items.splice(index, 1); } this.items.push(item); this.bytes += bytes; } shift(): OutboundMessage | undefined { const item = this.items.shift(); if (item) this.bytes -= Buffer.byteLength(JSON.stringify(item.payload)); return item; } drain(): readonly OutboundMessage[] { const values = [...this.items]; this.items.length = 0; this.bytes = 0; return values; } get sizeBytes() { return this.bytes; } get isClosed() { return this.closed; } }

export { DEVICE_CAPABILITIES, COMMAND_DESCRIPTORS };
