import { COMMAND_DESCRIPTORS, decodeCommandArguments, decodeCommandResult, decodeTerminalAdditive, decodeTerminalClient, type CommandFrame, type CommandResult, type DeviceCapability, type HostId, type Revision, type SessionId, type TerminalClientFrame, type TerminalId } from "@oh-my-pi/app-wire";

export interface OperationContext { hostId: HostId; sessionId?: SessionId; deviceId: string; connectionId: string; capabilities: ReadonlySet<DeviceCapability>; currentRevision?: Revision; expectedRevision?: Revision; abortSignal: AbortSignal; }
export interface DesktopOperationsAuthority {
  filesRead(args: CommandResult, context: OperationContext): Promise<CommandResult>; filesList(args: CommandResult, context: OperationContext): Promise<CommandResult>; filesDiff(args: CommandResult, context: OperationContext): Promise<CommandResult>; filesWrite(args: CommandResult, context: OperationContext): Promise<CommandResult>; filesPatch(args: CommandResult, context: OperationContext): Promise<CommandResult>;
  reviewRead(args: CommandResult, context: OperationContext): Promise<CommandResult>; reviewApply(args: CommandResult, context: OperationContext): Promise<CommandResult>; agentCancel(args: CommandResult, context: OperationContext): Promise<CommandResult>; bashRun(args: CommandResult, context: OperationContext): Promise<CommandResult>; termOpen(args: CommandResult, context: OperationContext): Promise<CommandResult>;
  catalogGet(args: CommandResult, context: OperationContext): Promise<CommandResult>; settingsRead(args: CommandResult, context: OperationContext): Promise<CommandResult>; settingsWrite(args: CommandResult, context: OperationContext): Promise<CommandResult>; configWrite(args: CommandResult, context: OperationContext): Promise<CommandResult>;
  previewLaunch(args: CommandResult, context: OperationContext): Promise<CommandResult>; previewState(args: CommandResult, context: OperationContext): Promise<CommandResult>; previewNavigate(args: CommandResult, context: OperationContext): Promise<CommandResult>; previewCapture(args: CommandResult, context: OperationContext): Promise<CommandResult>;
  terminalInput(frame: TerminalClientFrame, context: OperationContext): Promise<void>; terminalResize(frame: TerminalClientFrame, context: OperationContext): Promise<void>; terminalClose(frame: TerminalClientFrame, context: OperationContext): Promise<void>; terminalOutput?(frame: unknown, context: OperationContext): void;
}
export interface OperationCommandHandler { dispatch(command: CommandFrame, context: OperationContext): Promise<CommandResult>; routeTerminal(frame: unknown, context: OperationContext): Promise<void>; disconnect(connectionId: string, context: Omit<OperationContext, "connectionId" | "sessionId"> & { sessionId: SessionId }): Promise<void>; publishTerminalOutput(frame: unknown, owner: TerminalOwner): void; }
const CAPABILITY_BY_COMMAND: Record<string, DeviceCapability> = Object.fromEntries(Object.entries(COMMAND_DESCRIPTORS).map(([name, descriptor]) => [name, descriptor.capability])) as Record<string, DeviceCapability>;
const UNSAFE = new Set(["password", "passwd", "secret", "token", "credential", "api_key", "private_key"]);
function safeError(error: unknown): { code: string; message: string } { const code = error && typeof error === "object" && "code" in error && typeof error.code === "string" ? error.code : "OPERATION_FAILED"; const known: Record<string, string> = { STALE_REVISION:"session revision is stale", FORBIDDEN:"operation is not permitted", NOT_FOUND:"resource was not found", UNSUPPORTED:"operation is unsupported", ABORTED:"operation was cancelled", CONFLICT:"operation conflicts with current state", stale_revision:"session revision is stale", forbidden:"operation is not permitted", not_found:"resource was not found", unsupported:"operation is unsupported", aborted:"operation was cancelled", conflict:"operation conflicts with current state" }; return { code: known[code] ? code.toUpperCase() : "OPERATION_FAILED", message: known[code] ?? "operation failed" }; }
function cloneFreeze<T>(value: T): T { const copy = structuredClone(value); const freeze = (item: unknown): unknown => { if (!item || typeof item !== "object") return item; for (const child of Object.values(item)) freeze(child); return Object.freeze(item); }; return freeze(copy) as T; }
function invoke(authority: DesktopOperationsAuthority, command: string, args: CommandResult, context: OperationContext): Promise<CommandResult> {
  switch (command) { case "files.read": return authority.filesRead(args, context); case "files.list": return authority.filesList(args, context); case "files.diff": return authority.filesDiff(args, context); case "files.write": return authority.filesWrite(args, context); case "files.patch": return authority.filesPatch(args, context); case "review.read": return authority.reviewRead(args, context); case "review.apply": return authority.reviewApply(args, context); case "agent.cancel": return authority.agentCancel(args, context); case "bash.run": return authority.bashRun(args, context); case "term.open": return authority.termOpen(args, context); case "catalog.get": return authority.catalogGet(args, context); case "settings.read": return authority.settingsRead(args, context); case "settings.write": return authority.settingsWrite(args, context); case "config.write": return authority.configWrite(args, context); case "preview.launch": return authority.previewLaunch(args, context); case "preview.state": return authority.previewState(args, context); case "preview.navigate": return authority.previewNavigate(args, context); case "preview.capture": return authority.previewCapture(args, context); default: throw Object.assign(new Error("unsupported"), { code: "UNSUPPORTED" }); }
}
export interface TerminalOwner { connectionId: string; deviceId: string; hostId: HostId; sessionId: SessionId; terminalId: TerminalId; }
export class TerminalOwnerRegistry {
  readonly #owners = new Map<string, TerminalOwner>();
  claim(owner: TerminalOwner): void { if (this.#owners.has(owner.terminalId)) throw Object.assign(new Error("operation is not permitted"), { code: "FORBIDDEN" }); this.#owners.set(owner.terminalId, owner); }
  get(connectionId: string): TerminalOwner[] { return [...this.#owners.values()].filter(owner => owner.connectionId === connectionId); }
  assert(owner: TerminalOwner): void { const current = this.#owners.get(owner.terminalId); if (!current || current.connectionId !== owner.connectionId || current.deviceId !== owner.deviceId || current.hostId !== owner.hostId || current.sessionId !== owner.sessionId) throw Object.assign(new Error("operation is not permitted"), { code: "FORBIDDEN" }); }
  release(terminalId: TerminalId): void { this.#owners.delete(terminalId); }
  releaseConnection(connectionId: string): void { for (const [id, owner] of this.#owners) if (owner.connectionId === connectionId) this.#owners.delete(id); }
}
export class DesktopOperationDispatcher implements OperationCommandHandler {
  constructor(private readonly authority: DesktopOperationsAuthority, private readonly terminalOwners = new TerminalOwnerRegistry()) {}
  async dispatch(command: CommandFrame, context: OperationContext): Promise<CommandResult> {
    const descriptor = COMMAND_DESCRIPTORS[command.command]; const required = CAPABILITY_BY_COMMAND[command.command]; if (!descriptor || !required) throw Object.assign(new Error("operation is unsupported"), { code: "UNSUPPORTED" });
    if (command.hostId !== context.hostId || (descriptor.scope === "session" && (!command.sessionId || command.sessionId !== context.sessionId)) || (descriptor.scope === "host" && command.sessionId !== undefined)) throw Object.assign(new Error("operation is not permitted"), { code: "FORBIDDEN" });
    if (!context.capabilities.has(required)) throw Object.assign(new Error("operation is not permitted"), { code: "FORBIDDEN" });
    if (context.abortSignal.aborted) throw Object.assign(new Error("operation was cancelled"), { code: "ABORTED" });
    if (descriptor.revision === "required" && command.expectedRevision === undefined) throw Object.assign(new Error("expectedRevision is required"), { code: "STALE_REVISION" });
    if (descriptor.revisionOwner === "session") {
      if (descriptor.revision === "required" && (!context.currentRevision || command.expectedRevision !== context.currentRevision)) throw Object.assign(new Error("session revision is stale"), { code: "STALE_REVISION" });
      if (descriptor.revision === "optional" && command.expectedRevision !== undefined && (!context.currentRevision || command.expectedRevision !== context.currentRevision)) throw Object.assign(new Error("session revision is stale"), { code: "STALE_REVISION" });
    }
    if (descriptor.revision === "none" && command.expectedRevision !== undefined) throw Object.assign(new Error("expectedRevision is forbidden"), { code: "STALE_REVISION" });
    const args = cloneFreeze(decodeCommandArguments(command.command, command.args));
    const operationContext: OperationContext = { ...context, expectedRevision: command.expectedRevision };
    try { const result = await invoke(this.authority, command.command, args, operationContext); const decoded = cloneFreeze(decodeCommandResult(command.command, result)); if (command.command === "term.open" && typeof decoded.terminalId === "string" && context.sessionId) { try { this.terminalOwners.claim({ connectionId: context.connectionId, deviceId: context.deviceId, hostId: context.hostId, sessionId: context.sessionId, terminalId: decoded.terminalId as TerminalId }); } catch (error) { await this.authority.terminalClose({ v: "omp-app/1", type: "terminal.close", hostId: context.hostId, sessionId: context.sessionId, terminalId: decoded.terminalId as TerminalId }, operationContext); throw error; } } return decoded; } catch (error) { const safe = safeError(error); throw Object.assign(new Error(safe.message), { code: safe.code }); }
  }
  async routeTerminal(input: unknown, context: OperationContext): Promise<void> { const frame = decodeTerminalClient(input); if (frame.hostId !== context.hostId || frame.sessionId !== context.sessionId || !context.capabilities.has("term.input") && frame.type === "terminal.input" || !context.capabilities.has("term.resize") && frame.type === "terminal.resize" || !context.capabilities.has("term.open")) throw Object.assign(new Error("operation is not permitted"), { code: "FORBIDDEN" }); const owner: TerminalOwner = { connectionId: context.connectionId, deviceId: context.deviceId, hostId: context.hostId, sessionId: frame.sessionId, terminalId: frame.terminalId }; this.terminalOwners.assert(owner); const method = frame.type === "terminal.input" ? "terminalInput" : frame.type === "terminal.resize" ? "terminalResize" : "terminalClose"; await this.authority[method](frame, context); if (frame.type === "terminal.close") this.terminalOwners.release(frame.terminalId); }
  async disconnect(connectionId: string, context: Omit<OperationContext, "connectionId" | "sessionId"> & { sessionId: SessionId }): Promise<void> { const owners = this.terminalOwners.get(connectionId); const failures: unknown[] = []; for (const owner of owners) { try { await this.authority.terminalClose({ v: "omp-app/1", type: "terminal.close", hostId: owner.hostId, sessionId: owner.sessionId, terminalId: owner.terminalId }, { ...context, connectionId, sessionId: owner.sessionId }); } catch (error) { failures.push(error); } finally { this.terminalOwners.release(owner.terminalId); } } if (failures.length) throw Object.assign(new Error("one or more terminals failed to close"), { code: "OPERATION_FAILED" }); }
  publishTerminalOutput(frame: unknown, owner: TerminalOwner): void { this.terminalOwners.assert(owner); const decoded = decodeTerminalAdditive(frame); if (decoded.hostId !== owner.hostId || decoded.sessionId !== owner.sessionId || decoded.terminalId !== owner.terminalId) throw Object.assign(new Error("operation is not permitted"), { code: "FORBIDDEN" }); this.authority.terminalOutput?.(cloneFreeze(decoded), { hostId: owner.hostId, sessionId: owner.sessionId, deviceId: owner.deviceId, connectionId: owner.connectionId, capabilities: new Set(["term.open"]), abortSignal: new AbortController().signal }); if (decoded.type === "terminal.exit") this.terminalOwners.release(owner.terminalId); }
}
